[package]
name = "bfbot"
version = "0.1.0"
authors = ["Colin Reeder <vpzomtrrfrt@gmail.com>"]
edition = "2018"

[dependencies]
heliometer = "0.5.10"
noob = "2.0.0-alpha.1"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
futures = "0.3.5"
