[package]
name = "bfbot"
version = "0.1.0"
authors = ["Colin Reeder <vpzomtrrfrt@gmail.com>"]

[dependencies]
serenity = "0.5.1"
heliometer = { git = "https://github.com/PishLSDYUE/heliometer", rev = "7554e8" }
memstream = { git = "https://github.com/seanchen1991/rust-memstream", rev = "6945cb0" }
