[package]
name = "bfbot"
version = "0.1.0"
authors = ["Colin Reeder <vpzomtrrfrt@gmail.com>"]
edition = "2018"

[dependencies]
heliometer = "0.5.10"
noob = "2.0.0-alpha.1"
tokio = { version = "0.2.21", features = ["blocking", "rt-core", "macros"] }
futures = "0.3.5"
