[package]
name = "bfbot"
version = "0.1.0"
authors = ["Colin Reeder <vpzomtrrfrt@gmail.com>"]

[dependencies]
serenity = "0.6.0"
memstream = { git = "https://github.com/seanchen1991/rust-memstream", rev = "6945cb0" }
heliometer = "0.5.10"
